### PR TITLE
Sp having fun

### PR DESCRIPTION
**Pull request by sullypierce**
# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

Closes #[Enter issue #]

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions

Make sure to commit local changes in your branch before switching to master.
1. `git checkout master`
2. `git fetch --all`
3. `git checkout sp-having-fun`
4. do everything and enjoy, non mac users check that your computer doesn't break.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by JohnALong — DISMISSED** [review]
very cool & once the os was imported worked like a champ - still wish it would read off the meal eaten

**Review by rdbishop19 — CHANGES_REQUESTED** [review]
Getting this error message.
`'say' is not recognized as an internal or external command,
operable program or batch file.`

Maybe you need to add conditionals that check for only the mac system before the say commands?

**Review by treysuiter — DISMISSED** [review]
No error message on my terminal (pc).

**Review by treysuiter — APPROVED** [review]
No error message on pc.

**Review by rdbishop19 — APPROVED** [review]

**Review by JohnALong — APPROVED** [review]
looks good

**Pull request merged**
